USE [master]
GO

/****** Object:  Database [swinpayroll]    Script Date: 11/6/2022 1:55:27 PM ******/
CREATE DATABASE [swinpayroll]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'swinpayroll', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\swinpayroll.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'swinpayroll_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\swinpayroll_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [swinpayroll].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [swinpayroll] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [swinpayroll] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [swinpayroll] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [swinpayroll] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [swinpayroll] SET ARITHABORT OFF 
GO

ALTER DATABASE [swinpayroll] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [swinpayroll] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [swinpayroll] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [swinpayroll] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [swinpayroll] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [swinpayroll] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [swinpayroll] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [swinpayroll] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [swinpayroll] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [swinpayroll] SET  DISABLE_BROKER 
GO

ALTER DATABASE [swinpayroll] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [swinpayroll] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [swinpayroll] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [swinpayroll] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [swinpayroll] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [swinpayroll] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [swinpayroll] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [swinpayroll] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [swinpayroll] SET  MULTI_USER 
GO

ALTER DATABASE [swinpayroll] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [swinpayroll] SET DB_CHAINING OFF 
GO

ALTER DATABASE [swinpayroll] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [swinpayroll] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [swinpayroll] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [swinpayroll] SET QUERY_STORE = OFF
GO

ALTER DATABASE [swinpayroll] SET  READ_WRITE 
GO

